In [9]:
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
path_file = 'C:\\Users\\danie\\Documents\\tfm\\tfm\\other\\results_cross_entropy_loss_f1_score.xlsx'
df = pd.read_excel(path_file)

df.head()

  Audio Embedding  Experimento   f1-micro   f1-macro
0      Wav2Vec2.0            1  44.360523  33.738990
1      Wav2Vec2.0            2  44.727117  33.558480
2      Wav2Vec2.0            3  45.903020  34.956606
3          HuBERT            1  45.242217  34.644982
4          HuBERT            2  45.586083  33.987827

In [11]:
# Group by 'Audio Embedding' and compute mean and standard deviation for numeric columns
metric_cols = ['f1-micro', 'f1-macro']
grouped_stats = df.groupby('Audio Embedding')[metric_cols].agg(['mean', 'std'])

grouped_stats

                  f1-micro             f1-macro
                      mean       std       mean       std
Audio Embedding
HuBERT           45.697333  0.519749  34.562022  0.537537
UniSpeechSAT     45.035752  0.844540  34.174785  0.863446
Wav2Vec2.0       44.996887  0.805857  34.084692  0.760474
WavLM            43.586966  0.682015  32.476538  0.674770

In [12]:
grouped_stats = grouped_stats.round(3).astype(str)
grouped_stats

                f1-micro        f1-macro
                    mean    std     mean    std
Audio Embedding
HuBERT            45.697   0.52   34.562  0.538
UniSpeechSAT      45.036  0.845   34.175  0.863
Wav2Vec2.0        44.997  0.806   34.085   0.76
WavLM             43.587  0.682   32.477  0.675

In [15]:
df_final = pd.DataFrame()

for col in metric_cols:
    new_column = grouped_stats[col]['mean'].astype(str) + ' ± ' + grouped_stats[col]['std'].astype(str)
    df_final = pd.concat([df_final, new_column], axis=1)

df_final.columns = ['F1-micro', 'F1-macro']
df_final.head()

                    F1-micro        F1-macro
HuBERT         45.697 ± 0.52  34.562 ± 0.538
UniSpeechSAT  45.036 ± 0.845  34.175 ± 0.863
Wav2Vec2.0    44.997 ± 0.806   34.085 ± 0.76
WavLM         43.587 ± 0.682  32.477 ± 0.675

In [16]:
df_final = df_final.iloc[[2,0,1,3]]
df_final

                    F1-micro        F1-macro
Wav2Vec2.0    44.997 ± 0.806   34.085 ± 0.76
HuBERT         45.697 ± 0.52  34.562 ± 0.538
UniSpeechSAT  45.036 ± 0.845  34.175 ± 0.863
WavLM         43.587 ± 0.682  32.477 ± 0.675